
#ifndef _GLOBALS_H
#define _GLOBALS_H
#define MAX_MEMORY_SIZE 4096
#define LINESIZE 80
#define SYMBOL_MAX_SIZE 31
#define IC_INITIAL_SIZE 100
#define RESERVED_MEMORY 100
#define FALSE 0
#define TRUE 1
/* Bit-related info */
#define BITS_IN_WORD 14
#define BITS_IN_OPCODE 4
#define BITS_IN_ADDRESSING 2
#define BITS_IN_ARE 2
#define BITS_IN_REGISTER 3

/* Addressing methods bits location in the first word of a command */
#define SRC_TYPE_START_POS 4
#define SRC_TYPE_END_POS 5
#define DEST_TYPE_START_POS 2
#define DEST_TYPE_END_POS 3

#define BASE4_SIZE 8

typedef enum ARE
{
    ABSOLUTE,
    EXTERN,
    RELOCATABLE
} ARE;

typedef enum opcode
{
    MOV_OP,
    CMP_OP,
    ADD_OP,
    SUB_OP,
    NOT_OP,
    CLR_OP,
    LEA_OP,
    INC_OP,
    DEC_OP,
    JMP_OP,
    BNE_OP,
    RED_OP,
    PRN_OP,
    JSR_OP,
    RTS_OP,
    HLT_OP,
    NONE_OP,
    ERROR_OP
} opcode;

typedef enum reg
{
    R0,
    R1,
    R2,
    R3,
    R4,
    R5,
    R6,
    R7,
    R_NONE
} reg;

typedef enum attribute
{
    MDEFINE,
    CODE,
    DATA,
    EXTERNAL,
    ENTRY,
    NONE,
    ERROR
} attribute;

typedef enum instruction
{
    DEFINE_IN,
    STRING_IN,
    DATA_IN,
    EXTERN_IN,
    ENTRY_IN,
    NONE_IN,
    ERROR_IN
} instruction;

typedef enum addressing_type
{
    IMMEDIATE_ADDR,
    DIRECT_ADDR,
    INDEX_ADDR,
    REGISTER_ADDR,
    NONE_ADDR,
    ERROR_ADDR
} addressing_type;

typedef enum FILE_TYPE
{
    AS_FILE,
    AM_FILE,
    OB_FILE,
    ENT_FILE,
    EXT_FILE
} FILE_TYPE;

typedef enum errors
{
    WARNING_LINE_TOO_LONG=1,
    NUM_OUT_OF_RANGE,
    MACRO_UNEXPECTED_CHARS,
    MACRO_TOO_LONG,
    MACRO_CANT_BE_EMPTY,
    MACRO_INVALID_FIRST_CHAR,
    MACRO_ONLY_PRINTABLE,
    MACRO_CANT_BE_COMMAND,
    MACRO_ALREADY_EXISTS,
    MACRO_CANT_BE_REGISTER,
    MACRO_CANT_BE_INSTRUCT,
    LABEL_TOO_LONG,
    LABEL_CANT_BE_EMPTY,
    LABEL_INVALID_FIRST_CHAR,
    LABEL_ONLY_ALPHANUMERIC,
    LABEL_CANT_BE_COMMAND,
    LABEL_ALREADY_EXISTS,
    WARNING_LABEL_ONLY,
    LABEL_CANT_BE_REGISTER,
    LABEL_CANT_BE_INSTRUCT,
    DEFINE_EXPECTED_NUM,
    DEFINE_CANT_HAVE_LABEL,
    INSTRUCTION_NOT_FOUND,
    INSTRUCTION_NO_PARAMS,
    INSTRUCTION_INVALID_NUM_PARAMS,
    DATA_COMMAS_IN_A_ROW,
    DATA_EXPECTED_CONST,
    DATA_EXPECTED_COMMA_AFTER_NUM,
    DATA_UNEXPECTED_COMMA,
    DATA_LABEL_DOES_NOT_EXIST,
    STRING_TOO_MANY_OPERANDS,
    STRING_UNEXPECTED_CHARS,
    STRING_OPERAND_NOT_VALID,
    INVALID_ADDRESSING_TYPE,
    INDEX_EXPECTED_CLOSING_BRACKET,
    INDEX_INVALID_POSITION,
    EXPECTED_COMMA_BETWEEN_OPERANDS,
    EXTERN_NO_LABEL,
    EXTERN_INVALID_LABEL,
    EXTERN_TOO_MANY_OPERANDS,
    COMMAND_NOT_FOUND,
    COMMAND_UNEXPECTED_CHAR,
    COMMAND_TOO_MANY_OPERANDS,
    COMMAND_INVALID_ADDRESSING,
    COMMAND_INVALID_NUMBER_OF_OPERANDS,
    COMMAND_LABEL_DOES_NOT_EXIST,
    ENTRY_LABEL_DOES_NOT_EXIST,
    ENTRY_TOO_MANY_OPERANDS,
    ENTRY_CANT_BE_EXTERN,
    CANNOT_OPEN_FILE,
    FAILED_TO_ALLOCATE_MEMORY
} error;
#endif
